[package]
name = "squads-iced"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
base64 = "0.22.1"
bytes = "1.10.0"
directories = "6.0.0"
iced = {version = "0.13.1", features = ["image", "svg", "advanced"] }
rand = "0.9.0"
reqwest = {version = "0.12.12", features = ["blocking", "json"]}
scraper = "0.22.0"
serde = "1.0.218"
serde_json = "1.0.139"
sha2 = "0.10.8"
thirtyfour = "0.35.0"
tokio = "1.43.0"
unicode-properties = "0.1.3"
url = "2.5.4"
webbrowser = "1.0.3"


[[bin]]
name = "squads-iced"
path = "src/main.rs"
