[package]
name = "squads-iced"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version = "0.13.1", features = ["image"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
anyhow = "1.0"
parking_lot = "0.12"
base64 = "0.22.1"
fantoccini = { version = "0.21.2" }

[[bin]]
name = "squads-iced"
path = "src/main.rs"
